[build]
  base = "/"
  publish = "dist/"
  command = "yarn build"

[[redirects]]
  from = "/contribute/"
  to = "https://github.com/MisterPhilip/omnibug/blob/master/CONTRIBUTING.md"

[[redirects]]
  from = "/privacy-policy/"
  to = "/legal/privacy-policy/"

[[redirects]]
  from = "/terms-of-service/"
  to = "/legal/terms-of-service/"

[[redirects]]
  from = "/cookie-policy/"
  to = "/legal/cookie-policy/"

[[redirects]]
  from = "/features/"
  to = "/"

[[redirects]]
  from = "/help/chrome-missing-omnibug/"
  to = "/help/omnibug-does-not-show/"

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404
